### ISSUE TITLE
Example gets stuck at "Phase: awaitProvision"

### ISSUE THREAD

**Issue by webwurst** [integr8ly/keycloak-operator#87]
## Description
The provided example does not work for me, no Keycloak instance is created.

## Expected Behavior
Keycloak instance `minexample` gets provisioned.

## Actual Behavior
The operator sees the custom resource `minexample` showing up, but then gets stuck in phase 
`awaitProvision`. From the logs:
```
time="2019-08-03T13:03:43Z" level=info msg="Go Version: go1.10.8"
time="2019-08-03T13:03:43Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-08-03T13:03:43Z" level=info msg="operator-sdk Version: 0.0.7"
time="2019-08-03T13:03:43Z" level=info msg="operator config: resync: 60, sync-resources: true"
time="2019-08-03T13:03:43Z" level=info msg="Watching kc namespace: keycloak-test1"
time="2019-08-03T13:03:43Z" level=info msg="Watching namespace: keycloak-test1"
time="2019-08-03T13:15:21Z" level=info msg="Keycloak: minexample, Phase: "
time="2019-08-03T13:15:22Z" level=info msg="Keycloak: minexample, Phase: accepted"
time="2019-08-03T13:15:22Z" level=info msg="Keycloak: minexample, Phase: awaitProvision"
time="2019-08-03T13:15:43Z" level=info msg="Keycloak: minexample, Phase: awaitProvision"
time="2019-08-03T13:16:43Z" level=info msg="Keycloak: minexample, Phase: awaitProvision"
[...]
time="2019-08-03T13:27:44Z" level=info msg="Keycloak: minexample, Phase: awaitProvision"
```

## Environment
Setup with [kind](https://github.com/kubernetes-sigs/kind/):

```yaml
kind version: v0.4.0

nodeInfo:
    architecture: amd64
    bootID: fe360a03-dae6-4f91-8fc6-7f7f7d7fbd0a
    containerRuntimeVersion: containerd://1.2.6-0ubuntu1
    kernelVersion: 5.0.0-21-generic
    kubeProxyVersion: v1.15.0
    kubeletVersion: v1.15.0
    machineID: 24f74f0ebb994ed6930dfa696363494c
    operatingSystem: linux
    osImage: Ubuntu Disco Dingo (development branch)
    systemUUID: a7cffbcc-2d16-11b2-a85c-884f6370342e
```

## Steps to reproduce

```bash
# some config
base_url="https://raw.githubusercontent.com/integr8ly/keycloak-operator/master/deploy"
namespace="keycloak-test1"

# create cluster
kind create cluster
kind get kubeconfig-path --name kind | read -x KUBECONFIG

# apply customresourcedefinitions
kubectl apply -f "$base_url/crds/KeycloakRealm_crd.yaml"
kubectl apply -f "$base_url/crds/Keycloak_crd.yaml"

kubectl api-resources --api-group aerogear.org

# start keycloak-operator
kubectl create namespace "$namespace"
kubectl -n $namespace apply -f "$base_url/rbac.yaml"
kubectl -n $namespace apply -f "$base_url/operator.yaml"

kubectl -n $namespace logs -f -l name=keycloak-operator

# create keycloak and apply config for realm 
kubectl -n $namespace apply -f "$base_url/examples/keycloak_min.json"
kubectl -n $namespace apply -f "$base_url/examples/keycloakRealm.json"
```
